# Generated by Django 5.2.8 on 2025-12-12 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_rota', 'Em Rota'), ('disponivel', 'Disponível')], default='disponivel', max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_rota', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='planejada', max_length=20)),
                ('km_total_estimado', models.IntegerField(default=0)),
                ('tempo_estimado', models.IntegerField(default=0)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='logistica.motorista')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_rota'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=20, unique=True)),
                ('endereco_origem', models.CharField(max_length=255)),
                ('cep_origem', models.CharField(max_length=9)),
                ('endereco_destino', models.CharField(max_length=255)),
                ('cep_destino', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], default='pendente', max_length=20)),
                ('capacidade_necessaria', models.FloatField()),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='logistica.cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='logistica.motorista')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='logistica.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('van', 'Van'), ('caminhao', 'Caminhão'), ('moto', 'Moto')], max_length=20)),
                ('capacidade_maxima', models.FloatField()),
                ('km_atual', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20)),
                ('motorista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_atual', to='logistica.motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='logistica.veiculo'),
        ),
    ]
