# Generated by Django 5.2.8 on 2025-12-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(unique=True)),
                ('cnh', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_rota', 'Em Rota'), ('disponível', 'Disponivel')], default='ativo', max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.IntegerField(unique=True)),
                ('endereco_origem', models.CharField(max_length=100)),
                ('cep_origem', models.CharField(max_length=100)),
                ('endereco_destino', models.CharField(max_length=100)),
                ('cep_destino', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], default='pendente', max_length=100)),
                ('capacidade_necessaria', models.FloatField()),
                ('valor_frete', models.FloatField()),
                ('data_solicitacao', models.DateField()),
                ('data_entrega_prevista', models.DateField()),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('obs', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('van', 'Van'), ('caminha', 'Caminhão')], max_length=100)),
                ('capacidade_maxima', models.FloatField()),
                ('km_atual', models.IntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Manutenção')], default='disponivel', max_length=50)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_rota', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], default='planejada', max_length=20)),
                ('capacidade_total_utilizada', models.FloatField()),
                ('km_total_estimado', models.IntegerField()),
                ('tempo_estimado', models.DateField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.entrega')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.veiculo')),
            ],
        ),
    ]
