# Generated by Django 5.2.8 on 2025-12-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(choices=[('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=100),
        ),
    ]
