# Generated by Django 5.2.8 on 2025-12-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_alter_motorista_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100),
        ),
    ]
