# Generated by Django 5.2.8 on 2025-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='teste@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='rota',
            name='tempo_estimado',
            field=models.FloatField(),
        ),
    ]
