# Generated by Django 5.2.8 on 2025-12-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_cliente_email_cliente_nome_alter_rota_tempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='entrega',
        ),
        migrations.AddField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistica.rota'),
        ),
    ]
