# Generated by Django 5.2.8 on 2025-12-10 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_alter_entrega_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.rota'),
        ),
    ]
